### ISSUE TITLE
Описание

### ISSUE THREAD

**Issue by ptath** [wirenboard/wb-zigbee2mqtt#2]
Во-первых — спасибо за труд, оно работает =)

Второй день играюсь в wb6, прочел [это](https://wirenboard.com/wiki/index.php?title=ZigBee_Support&mobileaction=toggle_view_desktop#wb-zigbee2mqtt), поставил z2m, поставил сабж. Добавленное устройство появилось в веб-интерфейсе и в mqtt: /devices/0x00158d000397c458

Но там ведь те же самые данные что и в zigbee2mqtt/0x00158d000397c458!

Я не понимаю как можно практически это применить =)

**Comment by poglazoff** [comment]
Насколько я понимаю, у вас вопрос по тому, как использовать значения, полученные с устройства ZigBee.
Пожалуйста, сформулируйте вопрос максимально подробно, и задайте его на портале теподдержки support.wirenboard.com.

**Comment by ptath** [comment]
Не-а, я точно знаю что делать с данными из z2m. Я не могу понять зачем их дублировать в mqtt в топиках wb?

**Comment by poglazoff** [comment]
> Я не могу понять зачем их дублировать в mqtt в топиках wb?
Потому что для того, чтобы значения отображались нашим интерфейсом и обрабатывались стандартными процедурами нашего движка правил, они должны лежать в топиках со специально заданными именами: https://github.com/wirenboard/homeui/blob/master/conventions.md

**Comment by ptath** [comment]
Вооот, спасибо )

Я думал что правила могут из любого топика данные брать, в тч и из /zigbee2mqtt, тогда бы смысла не было. Получается что wb-zigbee2mqtt помогает преобразовать данные z2m в нужную для правил структуру.

Этого нет в описании ни тут, ни на вики wb.
